### ISSUE TITLE
Class 'Uuid' not found

### ISSUE THREAD

**Issue by ibrunotome** [Iconscout/laravel-auditing-elasticsearch#1]
Hi, when I try to update a model I got an error 500 with log message: "Class 'Uuid' not found".
The Uuid class of line 16 of ElasticSearch.php file. From what package comes this class?

**Comment by ibrunotome** [comment]
I've updated your class directly on vendor, using the webpatser/laravel-uuid package and it worked... do you want a pull request to facilitate this for everyone @rankarpan?

**Comment by rankarpan** [comment]
Thank @ibrunotome for reporting an issue. I've updated package.
