### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by ibrunotome** [Iconscout/laravel-auditing-elasticsearch#2]
Hi, can I ask you to upgrade the package, moving from webpaster/laravel-uuid to Ramsey\Uuid? because laravel already use this package on the Illuminate, so you will prevent to download another library that do the same.

And the support of owen-it/laravel-auditing v6 it's over, can you upgrade to the v7?

Thank you!

**Comment by rankarpan** [comment]
Hi @ibrunotome,
Thanks for your suggestion. Sure we'll upgrade this driver to make it compatible with upgrade version of owen-it/laravel-auditing v7.

**Comment by ibrunotome** [comment]
Thank you!
